### ISSUE TITLE
Currently broken with Discord Overlay Update (Class names)

### ISSUE THREAD

**Issue by Tenebrosful** [Minepatcher/Vtuber-Discord-Streamkit-Overlay-CSS#2]
Hello,

this overlay currently don't work anymore because Discord updated there overlay and changed class names and how id works, more information in the pull request (that need id fix) #1

**Comment by Minepatcher** [comment]
Thank you for the update! I will look into this and try to update this accordingly. It may take a couple days due to holidays.

**Comment by Minepatcher** [comment]
CSS has been updated. I have removed the default in place of purely Flexbox.
Thank you.
